apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{NAME}}
  namespace: openpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{NAME}}
  template:
    metadata:
      labels:
        app: {{NAME}}
    spec:
      containers:
        - name: {{NAME}}
          image: openpulse/standard:0.1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: openpulse-env
          workingDir: /app/services/{{DIR}}
          command: ["sh", "-c", "{{CMD}}"]
---
apiVersion: v1
kind: Service
metadata:
  name: {{NAME}}
  namespace: openpulse
spec:
  selector:
    app: {{NAME}}
  ports:
    - name: http
      port: {{PORT}}
      targetPort: {{PORT}}
