apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openpulse
resources:
  - namespace.yaml
  - configmap.yaml
  - ingestion-gateway.yaml
  - connector-service.yaml
  - normalization-service.yaml
  - query-api.yaml
  - consent-identity-service.yaml
  - governance-agent.yaml
  - ehr-integration.yaml
  - ops-console.yaml
